@startuml
autonumber

actor Client
participant CartController
participant CartService
participant IStorage

Client -> CartController: POST /api/product {productId, quantity}
alt quantity invalide
  CartController --> Client: 400 QUANTITY_INVALID
else quantity valide
  CartController -> CartService: getProduct(productId)
  CartService -> IStorage: getItem(productId)
  IStorage --> CartService: Product
  CartService --> CartController: Product

  CartController -> CartService: addIem(Product, quantity)
  CartService -> IStorage: checkStock(productId)
  IStorage --> CartService: stock
  CartService -> IStorage: addItem(Product, quantity)
  IStorage --> CartService: StorageItem
  CartService --> CartController: StorageItem

  CartController -> CartService: checkStock(productId)
  CartService -> IStorage: checkStock(productId)
  IStorage --> CartService: remainingStock
  CartService --> CartController: remainingStock

  CartController --> Client: 201 {id, name, price, stock, quantity}
end
@enduml
