### Health
GET http://localhost:3000/api/health

### Liste films
GET http://localhost:3000/api/movies

### Recherche films
GET http://localhost:3000/api/movies?q=para

### Ajouter un film
POST http://localhost:3000/api/movies
Content-Type: application/json

{
  "title": "The Dark Knight",
  "director": "Christopher Nolan",
  "year": 2008,
  "genre": "Action"
}

### Supprimer un film
DELETE http://localhost:3000/api/movies/1

### Page home JSON
GET http://localhost:3000/api/pages/home

### Page catalog JSON
GET http://localhost:3000/api/pages/catalog?q=inception
