services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tp-mvc-pur-typescript-2h
    ports:
      - "3004:3000"
    environment:
      - PORT=3000
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./src:/app/src
      - /app/node_modules
    command: npm run dev
    restart: unless-stopped
