### Health
GET http://localhost:3004/api/health

### Liste films
GET http://localhost:3004/api/movies

### Ajouter film
POST http://localhost:3004/api/movies
Content-Type: application/json

{
  "title": "Interstellar",
  "director": "Christopher Nolan",
  "year": 2014,
  "genre": "Science-fiction"
}

### Supprimer film
DELETE http://localhost:3004/api/movies/1

### Home page API
GET http://localhost:3004/api/pages/home
