apiVersion: 1

groups:
  - orgId: 1
    name: starter-mvc-log-alerts
    folder: Observability
    interval: 1m
    rules:
      - uid: starter_mvc_error_logs_threshold
        title: Too many error logs (5m)
        condition: B
        data:
          - refId: A
            datasourceUid: loki
            relativeTimeRange:
              from: 300
              to: 0
            model:
              datasource:
                type: loki
                uid: loki
              editorMode: code
              expr: sum(count_over_time({service="starter-mvc", level="error"}[5m]))
              instant: true
              intervalMs: 1000
              maxDataPoints: 43200
              queryType: instant
              refId: A
          - refId: B
            datasourceUid: __expr__
            relativeTimeRange:
              from: 0
              to: 0
            model:
              conditions:
                - evaluator:
                    params:
                      - 5
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - A
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              refId: B
              type: threshold
        noDataState: NoData
        execErrState: Error
        for: 5m
        annotations:
          summary: Plus de 5 logs error sur 5 minutes.
        labels:
          severity: warning
