@startuml
left to right direction

actor "Visiteur" as Visitor
actor "Utilisateur inscrit" as Member
actor "Moderateur" as Moderator
actor "Administrateur" as Admin

Visitor <|-- Member
Member <|-- Moderator

rectangle "App Films d'art et essai" {
  usecase "Consulter catalogue" as UC1
  usecase "Rechercher film" as UC2
  usecase "Consulter fiche film" as UC3
  usecase "Poster un avis" as UC4
  usecase "Verifier contenu avis" as UC5
  usecase "Signaler un avis" as UC6
  usecase "Moderer les avis" as UC7
  usecase "Administrer les fiches films" as UC8
}

Visitor --> UC1
Visitor --> UC2
Visitor --> UC3
Member --> UC4
Member --> UC6
Moderator --> UC7
Admin --> UC8

UC4 .> UC5 : <<include>>
UC6 .> UC3 : <<extend>>

@enduml
