@startuml
left to right direction
skinparam packageStyle rectangle
skinparam shadowing false

actor Utilisateur as User

rectangle "Mini App Gestion de films" {
  usecase "Ajouter un film" as UC1
  usecase "Lister les films" as UC2
  usecase "Rechercher un film" as UC3
  usecase "Supprimer un film" as UC4
  usecase "Valider les champs" as UC5
  usecase "Afficher message erreur" as UC6
}

User --> UC1
User --> UC2
User --> UC3
User --> UC4

UC1 .> UC5 : <<include>>
UC1 .> UC6 : <<extend>>
UC3 .> UC6 : <<extend>>

@enduml
